FROM amazonlinux:2

RUN yum install -y gcc openssl-devel pkgconfig systemd-devel rsync

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

WORKDIR /build
COPY tools/ ./tools/

ENTRYPOINT ["tools/in_container_run.sh"]
